apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      name: todo-pod
      labels:
        app: todo
    spec:
      containers:
      - name: todo-container
        image: samiksha2905/todo-app:latest
        ports:
        - containerPort: 8000
