apiVersion: v1
kind: Pod
metadata:
  name: todo-app
  labels:
    type: todo-app
spec:
  containers:
    - name: co1
      image: samiksha2905/todo-app:latest
      ports:
        - containerPort: 8000
